#!/bin/sh -e

./configure \
	--prefix=/usr \
	--sysconfdir=/usr/share \
	--localstatedir=/var \
	--disable-python \
	--enable-static=yes \
	--with-cli=readline

make
cd py

gpep517 build-wheel \
	--wheel-dir ../.dist \
	--output-fd 3 3>&1 >&2

cd ..

make DESTDIR="$1" install

python -m installer -d "$1" .dist/*.whl

install -Dm755 nftables.run "$1/etc/sv/nftables/run"
install -Dm644 nftables.conf "$1/etc/nftables.conf"
install -dm755 "$1"/etc/nftables.d
install -dm750 "$1"/var/lib/nftables

