#!/bin/sh -e

# Apply kernel config, pulled from Alpines LTS 
mv lts.x86_64.config .config

make

install -Dm755 arch/x86/boot/bzImage "$1/boot/vmlinuz-$2_1"

make INSTALL_MOD_STRIP=1 modules_install
